package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaPedidos generated by hbm2java
 */
public class CategoriaPedidos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set pedidoses = new HashSet(0);

    public CategoriaPedidos() {
    }

	
    public CategoriaPedidos(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public CategoriaPedidos(int id, String nombre, Set pedidoses) {
       this.id = id;
       this.nombre = nombre;
       this.pedidoses = pedidoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }




}


