package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaProductos generated by hbm2java
 */
public class CategoriaProductos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set productoses = new HashSet(0);

    public CategoriaProductos() {
    }

	
    public CategoriaProductos(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public CategoriaProductos(int id, String nombre, Set productoses) {
       this.id = id;
       this.nombre = nombre;
       this.productoses = productoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


