package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Set productosEstacioneses = new HashSet(0);

    public Estaciones() {
    }

	
    public Estaciones(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Estaciones(int id, String nombre, String descripcion, Set productosEstacioneses) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productosEstacioneses = productosEstacioneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductosEstacioneses() {
        return this.productosEstacioneses;
    }
    
    public void setProductosEstacioneses(Set productosEstacioneses) {
        this.productosEstacioneses = productosEstacioneses;
    }




}


