package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Insumos generated by hbm2java
 */
public class Insumos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String unidadDeMedida;
     private float cantidadActual;
     private Set productosInsumoses = new HashSet(0);

    public Insumos() {
    }

	
    public Insumos(int id, String nombre, String unidadDeMedida, float cantidadActual) {
        this.id = id;
        this.nombre = nombre;
        this.unidadDeMedida = unidadDeMedida;
        this.cantidadActual = cantidadActual;
    }
    public Insumos(int id, String nombre, String unidadDeMedida, float cantidadActual, Set productosInsumoses) {
       this.id = id;
       this.nombre = nombre;
       this.unidadDeMedida = unidadDeMedida;
       this.cantidadActual = cantidadActual;
       this.productosInsumoses = productosInsumoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUnidadDeMedida() {
        return this.unidadDeMedida;
    }
    
    public void setUnidadDeMedida(String unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }
    public float getCantidadActual() {
        return this.cantidadActual;
    }
    
    public void setCantidadActual(float cantidadActual) {
        this.cantidadActual = cantidadActual;
    }
    public Set getProductosInsumoses() {
        return this.productosInsumoses;
    }
    
    public void setProductosInsumoses(Set productosInsumoses) {
        this.productosInsumoses = productosInsumoses;
    }




}


