package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1



/**
 * ProductosInsumos generated by hbm2java
 */
public class ProductosInsumos  implements java.io.Serializable {


     private ProductosInsumosId id;
     private Insumos insumos;
     private Productos productos;

    public ProductosInsumos() {
    }

    public ProductosInsumos(ProductosInsumosId id, Insumos insumos, Productos productos) {
       this.id = id;
       this.insumos = insumos;
       this.productos = productos;
    }
   
    public ProductosInsumosId getId() {
        return this.id;
    }
    
    public void setId(ProductosInsumosId id) {
        this.id = id;
    }
    public Insumos getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Insumos insumos) {
        this.insumos = insumos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


