package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int id;
     private CategoriaProductos categoriaProductos;
     private String nombre;
     private String descripcion;
     private int precio;
     private Set productosInsumoses = new HashSet(0);
     private Set productosEstacioneses = new HashSet(0);
     private Set productosPedidos = new HashSet(0);
     private int id_categoria_productos;

    public int getId_categoria_productos() {
        return id_categoria_productos;
    }

    public void setId_categoria_productos(int id_categoria_productos) {
        this.id_categoria_productos = id_categoria_productos;
    }

    public Productos() {
    }
    public Productos(int id,int id_categoria_productos, String nombre, String descripcion, int precio) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
        this.id_categoria_productos = id_categoria_productos;
    }

	
    public Productos(int id, CategoriaProductos categoriaProductos, String nombre, String descripcion, int precio) {
        this.id = id;
        this.categoriaProductos = categoriaProductos;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Productos(int id, CategoriaProductos categoriaProductos, String nombre, String descripcion, int precio, Set productosInsumoses, Set productosEstacioneses, Set productosPedidos) {
       this.id = id;
       this.categoriaProductos = categoriaProductos;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.productosInsumoses = productosInsumoses;
       this.productosEstacioneses = productosEstacioneses;
       this.productosPedidos = productosPedidos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CategoriaProductos getCategoriaProductos() {
        return this.categoriaProductos;
    }
    
    public void setCategoriaProductos(CategoriaProductos categoriaProductos) {
        this.categoriaProductos = categoriaProductos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Set getProductosInsumoses() {
        return this.productosInsumoses;
    }
    
    public void setProductosInsumoses(Set productosInsumoses) {
        this.productosInsumoses = productosInsumoses;
    }
    public Set getProductosEstacioneses() {
        return this.productosEstacioneses;
    }
    
    public void setProductosEstacioneses(Set productosEstacioneses) {
        this.productosEstacioneses = productosEstacioneses;
    }
    public Set getProductosPedidos() {
        return this.productosPedidos;
    }
    
    public void setProductosPedidos(Set productosPedidos) {
        this.productosPedidos = productosPedidos;
    }




}


