package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1



/**
 * ProductosEstaciones generated by hbm2java
 */
public class ProductosEstaciones  implements java.io.Serializable {


     private ProductosEstacionesId id;
     private Estaciones estaciones;
     private Productos productos;

    public ProductosEstaciones() {
    }

    public ProductosEstaciones(ProductosEstacionesId id, Estaciones estaciones, Productos productos) {
       this.id = id;
       this.estaciones = estaciones;
       this.productos = productos;
    }
   
    public ProductosEstacionesId getId() {
        return this.id;
    }
    
    public void setId(ProductosEstacionesId id) {
        this.id = id;
    }
    public Estaciones getEstaciones() {
        return this.estaciones;
    }
    
    public void setEstaciones(Estaciones estaciones) {
        this.estaciones = estaciones;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


