package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1



/**
 * ProductosInsumosId generated by hbm2java
 */
public class ProductosInsumosId  implements java.io.Serializable {


     private int idProducto;
     private int idInsumos;
     private float cantidad;

    public ProductosInsumosId() {
    }

    public ProductosInsumosId(int idProducto, int idInsumos, float cantidad) {
       this.idProducto = idProducto;
       this.idInsumos = idInsumos;
       this.cantidad = cantidad;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public int getIdInsumos() {
        return this.idInsumos;
    }
    
    public void setIdInsumos(int idInsumos) {
        this.idInsumos = idInsumos;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductosInsumosId) ) return false;
		 ProductosInsumosId castOther = ( ProductosInsumosId ) other; 
         
		 return (this.getIdProducto()==castOther.getIdProducto())
 && (this.getIdInsumos()==castOther.getIdInsumos())
 && (this.getCantidad()==castOther.getCantidad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProducto();
         result = 37 * result + this.getIdInsumos();
         result = 37 * result + (int) this.getCantidad();
         return result;
   }   


}


