package Modelo;
// Generated 25/07/2018 09:07:06 PM by Hibernate Tools 4.3.1



/**
 * ProductosPedido generated by hbm2java
 */
public class ProductosPedido  implements java.io.Serializable {


     private ProductosPedidoId id;
     private Pedidos pedidos;
     private Productos productos;

    public ProductosPedido() {
    }

    public ProductosPedido(ProductosPedidoId id, Pedidos pedidos, Productos productos) {
       this.id = id;
       this.pedidos = pedidos;
       this.productos = productos;
    }
   
    public ProductosPedidoId getId() {
        return this.id;
    }
    
    public void setId(ProductosPedidoId id) {
        this.id = id;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }




}


